import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderTop from "@/components/top-header/HeaderTop";
import MainHeader from "@/components/main-header/MainHeader";
import Navbar from "@/components/navbar/Navbar";
import MobileNavbar from "@/components/navbar/MobileNavbar";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderTop />
        <MainHeader />
        <Navbar />
        <MobileNavbar />
        {children}
      </body>
    </html>
  );
}
